[project]
name = "mdf-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ndi-python==5.1.1.1",
    "opencv-python>=4.11.0.86",
]
